apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: node-app-ai-backend-test
  description: Node app named node-app-ai-backend-test
  annotations:
    github.com/project-slug: arjun-mindsprint-udemy/node-app-ai-backend-test
    backstage.io/techdocs-ref: dir:.
    jenkins.io/job-full-name: node-app-test-folder/node-app-ai-backend-test
spec:
  type: service
  owner: development
  lifecycle: experimental
  providesApis:
    - node-app-ai-backend-test-api
